sensuserver:
  hostname: sensuserver
  image: sfrek/sensu:server
  environment:
    COMPONENT: server
  links:
    - redis
    - rabbitmq
  volumes:
    - ./server:/config

sensuapi:
  hostname: sensuapi
  image: sfrek/sensu:api
  environment:
    COMPONENT: api
  links:
    - redis
    - rabbitmq
  expose:
    - 4567
  volumes:
    - ./api:/config

sensuclient:
  hostname: sensuclient
  image: sfrek/sensu:client
  environment:
    COMPONENT: client
  links:
    - rabbitmq
  volumes:
    - ./client:/config

redis:
  image: redis

rabbitmq:
  image: rabbitmq:3-management
