consul:
  image: consul
  hostname: consul
  command: -server -bootstrap -ui-dir /ui
  ports:
    - "172.17.42.1:53:53/udp"

registrator:
  image: registrator
  links:
    - consul:consul.service.consul
  hostname: registrator
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: --internal consul://consul.service.consul:8500
