elasticsearch:
  image: elasticsearch:lastest

rabbitmq:
  image: rabbitmq:3-management

influxdb:
  image: tutum/influxdb:latest

grafana:
  image: grafana/grafana:latest

fluentd:
  image: sfrek/fluentd
  volumes:
    - /tmp/fluent.d:/fluent.d
