elasticsearch:
  image: elasticsearch:lastest

rabbitmq:
  image: rabbitmq:3-management

influxdb:
  image: tutum/influxdb:latest

grafana:
  image: grafana/grafana:latest

fluentd:
  image: sfrek/fluentd
  volumes:
    - /dockers/services/fluentd/fluent.d:/fluent.d
    - /srv/logs:/logs
